[package]
name = "fbsim-core"
version = "1.0.0-alpha.1"
authors = ["whatsacomputertho"]
edition = "2021"
description = "A library for american football simulation"
readme = "README.md"
homepage = "https://doc.rs/fbsim-core"
repository = "https://github.com/whatsacomputertho/fbsim-core"
license-file = "LICENSE"
keywords = ["football","simulation","model","library","fbsim"]
categories = ["games","simulation"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rand_distr = "0.4.3"
serde = { version = "1.0.217", features = ["derive"] }
